spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          clone-on-start: 'true'
          uri: https://github.com/haitt2381/pet-project-config
  application:
    name: config-server
server:
  port: '8082'